version: "3.9"
services:
  app:
    build: .
    image: users_api_service_app
    container_name: users_api_service_app
    ports:
      - 80:80
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql+mysqlconnector://editor:RG_+?d8djz=^+J6p@database/magnis_trainee
    depends_on:
      - db
    links: 
      - db:database
  db:
    image: mysql
    container_name: users_api_service_db
    ports:
      - 3306:3306
    volumes:
      - users_api_service_db:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: topsecret
      MYSQL_DATABASE: magnis_trainee
      MYSQL_USER: editor
      MYSQL_PASSWORD: RG_+?d8djz=^+J6p
volumes:
  users_api_service_db:
